security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15

    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_TEACHER: [ROLE_USER, ROLE_STUDENT]
        ROLE_ADMIN: [ROLE_USER, ROLE_STUDENT, ROLE_TEACHER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: app_user_provider
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
            json_login:
                check_path: /api/auth/token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~